version: '3.8'

services:
  postgres:
    image: postgres:13.15-bullseye
    container_name: database
    environment:
      POSTGRES_USER: thayaagh
      POSTGRES_PASSWORD: thayaagh
      POSTGRES_DB: thayaagh_database
    ports:
      - "5432:5432"
    networks:
      - thayaagh-network

  adminer:
    image: adminer:4.8.1-standalone
    container_name: db-mgmt
    environment:
      ADMINER_DEFAULT_SERVER: database
    ports:
      - "8080:8080"
    networks:
      - thayaagh-network

networks:
  thayaagh-network:
    driver: bridge

volumes:
  db-data: {}